Transition from number to bigint
Rpc-h/RPCh pull request #215
Opened 2023-02-13 16:38 UTC by ItsLuized

Closes #177

2023-02-16 20:43 UTC, diegoalzate commented on apps/discovery-platform/src/funding-service-api/index.spec.ts
> +        amount: BigInt("5").toString(),
I feel like this is just writing "5" but with extra steps

2023-02-16 20:45 UTC, diegoalzate commented on apps/discovery-platform/src/funding-service-api/index.spec.ts
> +        amount: BigInt("5").toString(),
if we are trying to express that a big int can come here in form of a string then thats fine, just in some places it is "5" and in others it is BigInt("5").toString().

2023-02-16 20:49 UTC, diegoalzate commented on apps/discovery-platform/src/graph-api/index.ts
> +// @ts-ignore
I think we can make this part ts compliant

2023-02-16 21:07 UTC, diegoalzate requested changes

2023-02-16 21:07 UTC, diegoalzate commented on apps/funding-service/src/entry-server/middleware/index.ts
> +    }
amount being inside the body is part of the validation done in express server [here](https://github.com/Rpc-h/RPCh/blob/bccebb35436508d7b8e18164a431ec4dd8668a91/apps/funding-service/src/entry-server/index.ts#L52)

2023-02-16 21:07 UTC, diegoalzate commented on apps/funding-service/src/queue/index.spec.ts
> +  it.only("should fail if signer does not have enough to fund request", async function () {
remove this .only

2023-02-21 10:46 UTC, nionis approved these changes

2023-02-21 10:46 UTC, nionis commented on apps/funding-service/src/db/index.spec.ts
> +    instance.public.interceptQueries((sql) => {
lets add a comment to what this does

2023-02-21 11:29 UTC, nionis commented on apps/funding-service/src/db/index.spec.ts
> +    instance.public.interceptQueries((sql) => {
and if its used in many places, we should somehow make it re-usable so its not copy pasted

2023-02-21 13:29 UTC, nionis approved these changes

2023-02-21 13:29 UTC, nionis commented on packages/common/src/fixtures.ts
> +import { IMemoryDb } from "pg-mem";
```suggestion
import type { IMemoryDb } from "pg-mem";
```

2023-02-21 14:17 UTC, nionis approved these changes

2023-02-21 14:18 UTC, merged