External provider impl
Rpc-h/RPCh pull request #327
Opened 2023-04-07 15:26 UTC by ItsLuized

This pull request aims to implement the RPChProvider as an External Provider type in order to use it with wallets that use Web3Provider type providers.

In Frame wallet they use their own provider called `eth-provider`, this provider is more similar to Web3Provider instead of JsonRpcProvider. In order to implement RPCh in this wallet we need to create a Provider type more similar to Web3Provider to use the same methods and return types they use.

2023-04-07 15:27 UTC, ItsLuized commented
Unit tests for this ExternalProvider type are still missing

2023-04-10 14:27 UTC, ItsLuized commented
To inject the provider in Frame, it must be created in main.chains/index.js in the function _createProvider(). 
https://github.com/Rpc-h/extension-frame/blob/develop/main/chains/index.js#LL65C1-L66C1

No blockers until the moment.

2023-04-14 15:37 UTC, diegoalzate commented
@nionis Not sure if the new provider should be moved to a separate file, or we rename ethers package to providers

2023-04-14 15:59 UTC, nionis commented
@diegoalzate it should be a new adaptor in `packages`

2023-04-18 08:15 UTC, nionis requested changes
README references wrong ethereum-provider GH project

2023-04-19 13:02 UTC, diegoalzate commented
Adaptor now only does what EIP 1993 states. removing any custom behaviour from specific wallets.

2023-04-20 10:49 UTC, nionis approved these changes
please resolve conflicts and merge

2023-04-20 10:52 UTC, nionis commented on packages/ethereum-provider/README.md
> +    client: '',
add same `client` text as in the ethers README

2023-04-20 13:13 UTC, merged