[hotfix] Turn message into segments before sending.
Rpc-h/RPCh pull request #75
Opened 2022-12-08 19:47 UTC by ItsLuized

2022-12-09 20:30 UTC, nionis requested changes

2022-12-09 20:30 UTC, nionis commented on apps/exit-node/src/index.ts
> +        await ops.hoprd.sendMessage({
```suggestion
        ops.hoprd.sendMessage({
```

2022-12-09 20:30 UTC, nionis commented on apps/exit-node/src/index.ts
> +        await ops.hoprd.sendMessage({
let's keep the use of `hoprd.sendMessage` consistent and remove `await` similar to https://github.com/Rpc-h/RPCh/blob/a9e6b9368b7a664d8d1c42298e2dcbe7bc323b4c/packages/sdk/src/index.ts#L191-L198
we might change this later on

2022-12-09 22:43 UTC, camilovegag approved these changes
👍

2022-12-12 11:48 UTC, nionis approved these changes

2022-12-12 12:38 UTC, merged